---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: irfan-app
  labels:
    app: irfan-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: irfan-app
  template:
    metadata:
      labels:
        app: irfan-app
    spec:
      containers:
      - name: irfan-container
        image: 727646491422.dkr.ecr.us-east-2.amazonaws.com/amazon-prime:latest
        ports:
        - containerPort: 3000
...
